export const GET_ALL_ACCOUNTS = "GET_ALL_ACCOUNTS"
export const SEARCH_ACCOUNTS = "SEARCH_ACCOUNTS"
export const SEARCH_ACCOUNTS_BY_CODE = "SEARCH_ACCOUNTS_BY_CODE"
export const Clear_STATE= "Clear_STATE"